-- Add stroke risk analysis columns to visits table
ALTER TABLE visits 
ADD COLUMN IF NOT EXISTS retinal_image_path TEXT,
ADD COLUMN IF NOT EXISTS retinal_image_source TEXT CHECK (retinal_image_source IN ('camera', 'gallery', 'upload')),
ADD COLUMN IF NOT EXISTS stroke_risk_percentage DECIMAL(5,2),
ADD COLUMN IF NOT EXISTS stroke_risk_level TEXT CHECK (stroke_risk_level IN ('Low', 'Moderate', 'High', 'Critical', 'Insufficient Quality')),
ADD COLUMN IF NOT EXISTS risk_factors JSONB,
ADD COLUMN IF NOT EXISTS ai_recommendations TEXT,
ADD COLUMN IF NOT EXISTS ai_analysis_date TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS ai_model_version TEXT,
ADD COLUMN IF NOT EXISTS image_quality_score DECIMAL(5,2);

-- Add comment for documentation
COMMENT ON COLUMN visits.retinal_image_path IS 'File path or URI of the analyzed retinal image';
COMMENT ON COLUMN visits.retinal_image_source IS 'Source of the image: camera, gallery, or upload';
COMMENT ON COLUMN visits.stroke_risk_percentage IS 'AI-calculated stroke risk percentage (0-100)';
COMMENT ON COLUMN visits.stroke_risk_level IS 'Categorical risk level: Low, Moderate, High, Critical, or Insufficient Quality';
COMMENT ON COLUMN visits.risk_factors IS 'JSON object containing detailed AI findings and biomarkers';
COMMENT ON COLUMN visits.ai_recommendations IS 'Clinical recommendations generated by AI';
COMMENT ON COLUMN visits.ai_analysis_date IS 'Timestamp when AI analysis was performed';
COMMENT ON COLUMN visits.ai_model_version IS 'Version of AI model used for analysis (e.g., gemini-2.5-pro)';
COMMENT ON COLUMN visits.image_quality_score IS 'Quality score of the retinal image (0-100)';